import { assetUrl } from "./assets";
import { newIso, type CatalogItem, type IsoDocument, type PipeSpec } from "../core/model";

/** Built-in specifications served from library/ (generated by scripts/build-piping-library.py). */
export interface LibrarySpecSummary {
  slug: string;
  id: string;
  name: string;
  material: string;
  service: string;
  rating: string;
  rowCount: number;
}

let index: Promise<LibrarySpecSummary[]> | null = null;
export function loadSpecIndex(): Promise<LibrarySpecSummary[]> {
  index ??= fetch(assetUrl("library/index.json"))
    .then((r) => {
      if (!r.ok) throw new Error("The specification library could not load.");
      return r.json() as Promise<LibrarySpecSummary[]>;
    })
    .catch((e) => {
      index = null;
      throw e;
    });
  return index;
}

/**
 * Load a library specification ready to embed in a drawing. Catalogue ids are unique across every
 * specification in a document, so they are namespaced by the (possibly renamed) specification id.
 */
export async function loadLibrarySpec(slug: string, doc?: IsoDocument): Promise<PipeSpec> {
  const response = await fetch(assetUrl("library/specs/" + encodeURIComponent(slug) + ".json"));
  if (!response.ok) throw new Error("The specification could not load.");
  const raw = (await response.json()) as PipeSpec & { branchCodes?: unknown; unsizedItems?: unknown };
  delete raw.branchCodes;
  delete raw.unsizedItems;
  return namespaceSpec(raw, uniqueSpecId(raw.id, doc));
}

export function uniqueSpecId(base: string, doc?: IsoDocument): string {
  const taken = new Set(doc?.specs.map((s) => s.id) ?? []);
  let id = base,
    n = 2;
  while (taken.has(id)) id = base + "-" + n++;
  return id;
}

export function namespaceSpec(spec: PipeSpec, id: string): PipeSpec {
  const strip = (key: string) => key.replace(/^[^:/]*[:/]/, "");
  return {
    ...spec,
    id,
    fittings: spec.fittings.map((f: CatalogItem) => ({ ...f, id: id + ":" + strip(f.id) })),
  };
}

/** A new drawing starts on the standard library's general-service spec A, falling back to the built-in spec offline. */
export async function newIsoWithDefaultSpec(): Promise<IsoDocument> {
  const doc = newIso();
  try {
    doc.specs = [await loadLibrarySpec("a")];
  } catch {
    // Keep the bundled Schedule 40 specification.
  }
  return doc;
}

/** Most routing starts at 2″; small-bore-first specifications should not default to ⅛″. */
export const defaultNps = (spec: PipeSpec) =>
  spec.sizes.find((s) => s.nps === 2)?.nps ?? spec.sizes[0]?.nps ?? 2;
