"""Generates the Spoolyard mark: an isometric pipe spool — a pipe between two bolted flanges — in true
isometric projection, with hidden lines resolved by painting back to front. Writes the README lockups,
the app icon and src/editor/mark-geometry.ts so every surface uses identical geometry."""
import math, json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
C30 = math.cos(math.pi / 6)

def iso(x, y, z):
    return ((x - y) * C30, -(x + y) * 0.5 - z)

def ring(xc, r, n=96):
    return [iso(xc, r * math.cos(2 * math.pi * k / n), r * math.sin(2 * math.pi * k / n)) for k in range(n)]

def hull(points):
    pts = sorted(set((round(x, 4), round(y, 4)) for x, y in points))
    def cross(o, a, b): return (a[0]-o[0])*(b[1]-o[1]) - (a[1]-o[1])*(b[0]-o[0])
    lower, upper = [], []
    for p in pts:
        while len(lower) >= 2 and cross(lower[-2], lower[-1], p) <= 0: lower.pop()
        lower.append(p)
    for p in reversed(pts):
        while len(upper) >= 2 and cross(upper[-2], upper[-1], p) <= 0: upper.pop()
        upper.append(p)
    return lower[:-1] + upper[:-1]

# World geometry (arbitrary units). The pipe runs along +x; the viewer looks from (-1,-1,+1),
# so the flange at smaller x is the front one.
H, R, RP, TF, RI, RB = 10.5, 12.5, 6.0, 3.4, 4.2, 9.2
shapes = {
    "backRim": hull(ring(H, R) + ring(H + TF, R)),
    "backFace": ring(H, R),
    "pipe": hull(ring(-H, RP) + ring(H, RP)),
    "frontRim": hull(ring(-H, R) + ring(-H - TF, R)),
    "frontFace": ring(-H - TF, R),
    "bore": ring(-H - TF, RI),
}
# Eight bolt holes, numbered in the cross-pattern tightening order 1-5-3-7-2-6-4-8.
order = [0, 4, 2, 6, 1, 5, 3, 7]
bolts = [iso(-H - TF, RB * math.cos(2 * math.pi * k / 8 + math.pi / 8), RB * math.sin(2 * math.pi * k / 8 + math.pi / 8)) for k in range(8)]
bolts = [bolts[k] for k in order]

xs = [x for s in shapes.values() for x, _ in s]; ys = [y for s in shapes.values() for _, y in s]
minx, maxx, miny, maxy = min(xs), max(xs), min(ys), max(ys)
SIZE, PAD = 64.0, 5.0
k = (SIZE - 2 * PAD) / max(maxx - minx, maxy - miny)
ox = (SIZE - (maxx - minx) * k) / 2 - minx * k
oy = (SIZE - (maxy - miny) * k) / 2 - miny * k
T = lambda p: (round(p[0] * k + ox, 2), round(p[1] * k + oy, 2))
def path(pts): return "M" + " L".join(f"{x} {y}" for x, y in map(T, pts)) + " Z"
geo = {name: path(pts) for name, pts in shapes.items()}
geo["bolts"] = [list(T(b)) for b in bolts]
geo["boltR"] = round(1.15 * k, 2)
geo["stroke"] = 2.4

(ROOT / "src/editor/mark-geometry.ts").write_text(
    "// Generated by scripts/brand.py — isometric pipe spool, 64×64. Do not edit by hand.\n"
    "export const MARK = " + json.dumps(geo, indent=2) + " as const\n")

def mark_svg(ink, paper, accent, cls=True, scale=1.0, tx=0.0, ty=0.0, hole=None):
    a = lambda c, d: f' class="{c}" style="--d:{d}s"' if cls else ""
    out = [f'<g transform="translate({tx} {ty}) scale({scale})" stroke="{ink}" stroke-width="{geo["stroke"]}" stroke-linejoin="round" fill="{paper}">']
    out.append(f'<path{a("o", .05)} pathLength="1" d="{geo["backRim"]}"/>')
    out.append(f'<path{a("o", .15)} pathLength="1" d="{geo["backFace"]}"/>')
    out.append(f'<path{a("o", .3)} pathLength="1" d="{geo["pipe"]}"/>')
    out.append(f'<path{a("o", .45)} pathLength="1" d="{geo["frontRim"]}"/>')
    out.append(f'<path{a("o", .55)} pathLength="1" d="{geo["frontFace"]}"/>')
    bore = f'fill="{hole}" stroke="{ink}"' if hole else f'fill="{ink}" stroke="none"'
    out.append(f'<path{a("bore", .7)} d="{geo["bore"]}" {bore}/>')
    for i, (x, y) in enumerate(geo["bolts"]):
        out.append(f'<circle{a("b", round(.8 + i * .09, 2))} cx="{x}" cy="{y}" r="{geo["boltR"]}" fill="{accent}" stroke="none"/>')
    out.append("</g>")
    return "".join(out)

STYLE = """
    @keyframes draw { from { stroke-dashoffset: 1 } }
    @keyframes fill { from { fill-opacity: 0 } }
    @keyframes pop { 0% { opacity: 0; transform: scale(.2) } 70% { opacity: 1; transform: scale(1.35) } }
    @keyframes rise { from { opacity: 0; transform: translateY(5px) } }
    @keyframes cycle { 0%, 90% { opacity: 1 } 95% { opacity: 0 } 100% { opacity: 1 } }
    .o { stroke-dasharray: 1; animation: draw .6s cubic-bezier(.4,0,.2,1) var(--d) backwards, fill .4s ease var(--d) backwards }
    .bore { animation: fill .4s ease var(--d) backwards }
    .b { transform-box: fill-box; transform-origin: center; animation: pop .35s cubic-bezier(.34,1.56,.64,1) var(--d) backwards }
    .w { animation: rise .6s cubic-bezier(.4,0,.2,1) 1.2s backwards }
    .t { animation: rise .6s cubic-bezier(.4,0,.2,1) 1.45s backwards }
    @media (prefers-reduced-motion: reduce) { .o, .bore, .b, .w, .t { animation: none } }
"""
FONT = "ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif"

def lockup(ink, paper, accent, muted, name, hole=None):
    svg = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 520 132" width="520" height="132" role="img" aria-label="spoolyard">
  <!-- Spoolyard lockup. The spool draws in — back flange, pipe, front flange — the bolts pop in the
       cross-pattern tightening order, then the wordmark rises. Resting state is the complete logo
       (intros use fill-mode backwards), so renderers without animation still show it. -->
  <style>{STYLE}  </style>
  {mark_svg(ink, paper, accent, scale=1.85, tx=0, ty=6, hole=hole)}
  <text class="w" x="134" y="82" font-size="64" font-weight="700" letter-spacing="-2.4" font-family="{FONT}"><tspan fill="{ink}">spool</tspan><tspan fill="{accent}">yard</tspan></text>
  <text class="t" x="137" y="112" font-size="13.5" font-weight="600" letter-spacing="3" fill="{muted}" font-family="{FONT}">PIPING ISOMETRICS · SPOOL DRAWINGS</text>
</svg>
'''
    (ROOT / "assets" / name).write_text(svg)

INK, ACCENT = "#14202e", "#ee6a1c"
lockup(INK, "#ffffff", ACCENT, "#5b6b7c", "spoolyard-logo.svg")
lockup("#e8eef5", "#0d1117", "#ff8a3d", "#8b9bab", "spoolyard-logo-dark.svg", hole="#05080c")

# App icon: the spool in paper strokes on an ink tile.
icon = f'''<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 64 64">
  <rect x="3" y="3" width="58" height="58" rx="13.5" fill="{INK}"/>
  {mark_svg("#f4f1ea", INK, ACCENT, cls=False, scale=0.8, tx=6.4, ty=6.4, hole="#070d14")}
</svg>
'''
(ROOT / "assets" / "icon.svg").write_text(icon)
(ROOT / "public" / "favicon.svg").write_text(icon.replace('width="1024" height="1024" ', ""))
print("ok", geo["boltR"], k)
